* Accounting App
  [[https://img.shields.io/circleci/build/gh/wildwestrom/accounting-app/main.svg]]

  The site is up and running on Netlify.\\
  https://accounting-app-8976546487.netlify.app/

** Develop
Before running for the first time run:
#+begin_src shell
yarn deps
#+end_src

*** CLI

#+begin_src shell
yarn watch
#+end_src

*** [[https://cider.mx/][CIDER]] (Emacs)
    - =M-x=
    - =sesman-start=
    - Select command: =cider-connect-cljs=
    - host: =localhost=
    - port: =3333=
    - repl-type: =shadow=
    - build: =:app= or =:test=

** License
Accounting App: Demo Project\\
Copyright © 2021 Christian Westrom

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

The rest is my own original work unless otherwise specified.
