# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2.1

jobs:
  test:
    docker:
      - image: circleci/clojure:tools-deps-node

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          name: Restore clojure dependency cache
          keys:
            - v1-dependencies-clj-{{ checksum "deps.edn" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-clj-
      - restore_cache:
          name: Restore node dependency cache
          keys:
            - v1-dependencies-node-{{ checksum "yarn.lock" }}
            - v1-dependencies-node-

      # install dependencies
      - run: yarn deps
      # test
      - run: yarn test
      # release
      - run: yarn release

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-clj-{{ checksum "deps.edn" }}

      - save_cache:
          paths:
            - ~/.cache/yarn
            - ~/repo/node_modules
          key: v1-dependencies-node-{{ checksum "yarn.lock" }}

      - persist_to_workspace:
         root: ~/
         paths:
          - repo/
  deploy:
    docker: circleci/node:latest
    working_directory: ~/
    # remember to cd into `~/repo/`

    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: just testing some stuff
          command: |
            pwd
            ls -la

workflows:
  test-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          # filters:
          #   branches:
          #     only: master
