# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

jobs:
  build:
    docker:
      - image: circleci/clojure:tools-deps-node

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          name: Restore clojure dependency cache
          keys:
            - v1-dependencies-clj-{{ checksum "deps.edn" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-clj-
      - restore_cache:
          name: Restore node dependency cache
          keys:
            - v1-dependencies-node-{{ checksum "yarn.lock" }}
            - v1-dependencies-node-

      # build!
      - run: yarn release

      - persist_to_workspace:
         root: ~/
         paths:
          - repo/public

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-clj-{{ checksum "deps.edn" }}

      - save_cache:
          paths:
            - ~/.cache/yarn
            - ~/repo/node_modules
          key: v1-dependencies-node-{{ checksum "yarn.lock" }}

      - store_artifacts:
          path: ~/repo/public
  deploy:
    executor: heroku/default
    working_directory: ~/
    steps:
      - attach_workspace:
          at: ~/
      - heroku/install
      - run:
          command: >
            echo "The command above installs Heroku, the command below deploys.
            What you do inbetween is up to you!"
      - heroku/deploy-via-git


workflows:
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          # filters:
          #   branches:
          #     only: master
